### ISSUE TITLE
consistency of dependencies type in package.json

### ISSUE THREAD

**Issue by rondinif** [renaco/webpack-pug-scss-ts#2]
Hi,
it would be cleaner that the dependencies are specified in the specific group of appertenence so for consistency and 
according to [Specifying dependencies and devDependencies in a package.json file](https://docs.npmjs.com/specifying-dependencies-and-devdependencies-in-a-package-json-file) I would like to move in devDependecies those that actually are not dependiecies for the runtime code

**Comment by renaco** [comment]
Thanks for your feedback, I did close the issue because was fix in  https://github.com/renaco/webpack-pug-scss-ts/pull/3
